encoding: utf-8
name: Gautham Vasan
url: https://gauthamvasan.github.io/animated_clay
author:
  name: Gautham Vasan
  email: gauthamv.529@gmail.com
  description: "PhD student at the University of Alberta. I'm interested in building machines with human-like intelligence."
permalink: /posts/:title/
baseurl: /animated_clay/
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}
