# Welcome to Jekyll!

# Website settings
title: "Gautham Vasan"
description: "Gautham's blog,use Jekyll and github pages."
keywords: "Gautham, Vasan,Jalpc,blog,Jekyll,github,gh-pages"

baseurl: "/"
url: "https://gauthamvasan.github.io/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Gautham Vasan'
  first_name: 'Gautham'
  last_name: 'Vasan'
  email: 'gauthamv.529@gmail.com'
  facebook_username: 'gautham.vasan'
  github_username: 'gauthamvasan'
  head_img: 'static/img/landing/Gautham.jpg'
  linkedin: 'https://ca.linkedin.com/in/gauthamvasan'
  resume: 'My Resume' 

# social link
gauthamv:
  first_name: 'Gautham'
  last_name: 'Vasan'
  description: 'Engineer'
  link: 'https://www.goodreads.com/user/show/29446357-gautham-vasan'
  email: 'gauthamv.529@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  contact: 'Link'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'
  tiadc:
    name: 'Texas Instruments Innovation Challenge 2014'
    url: 'https://www.youtube.com/watch?v=qiCRSVuftFQ'
    pdf: 'http://arxiv.org/abs/1412.0591'
    img: 'static/img/landing/ti.jpg'
  ardrone:
    name: 'ArDrone'
    url: 'https://drive.google.com/open?id=0B78EAxFuk2RLWUsyOWdTMTdYak0'
    url_2: 'https://drive.google.com/open?id=0B78EAxFuk2RLOGlDSXYyQkpnb2c'
    img: 'static/img/landing/ardrone.jpg'
  hex:
    name: 'Neurohex'
    url: '/gauthamvasan/Neurohex'
    pdf: 'https://arxiv.org/abs/1604.07097 '	
    img: 'static/img/landing/hex.jpg'
  rl:
    name: 'RL 101'
    url: '/gauthamvasan/Adaptive-Prosthetics'
    img: 'static/img/landing/rl.png'
  bento:
    name: 'Bento Arm'
    url: 'https://drive.google.com/open?id=0B8-iXsaYqsxmUWJnTkpvMkplMXM'
    img: 'static/img/landing/bento.jpg'
  mslesion:
    name: 'MS Lesion Segmentation'
    url: 'https://drive.google.com/file/d/0B8-iXsaYqsxmLVFMcmh4NGstVjg/view?usp=sharing'
    img: 'static/img/landing/mslesion.jpg'
  openai:
    name: 'Open AI Gym'
    url: '/gauthamvasan/OpenAI-Gym'
    img: 'static/img/landing/openai.jpg'
# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-81355705-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sitemap
gems:
  - jekyll-sitemap
